
package javaapplication13;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class Adivinador extends javax.swing.JFrame{
    private arbolAVL arbol;
    private boolean respuesta;
    ImageIcon imgPersonaje;
    

    /**
     * Creates new form Adivinador
     */
    public Adivinador() {
        
        initComponents();
 
    imagen.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kindpng_990704.png")).getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH)));
    jLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aladin_room_akinator.jpg")).getImage().getScaledInstance(948, 506, Image.SCALE_SMOOTH)));
    if(arbol==null){
       lblResultado.setText("No conozco ningun personaje, ingresa uno");
    }
    btnIniciar.setVisible(false);
    btnSi.setVisible(false);
    btnNo.setVisible(false);
    lblPregunta.setVisible(false);

    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtPersonaje = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSi.setText("SI");
        btnSi.setEnabled(false);
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 179, -1, -1));

        btnNo.setText("NO");
        btnNo.setEnabled(false);
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 179, -1, -1));

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(255, 51, 51));
        lblPregunta.setText("Pregunta");
        getContentPane().add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 113, 407, 48));
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 75, 308, 309));

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 51, 51));
        lblResultado.setText("El personaje que estas pensando es:");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 243, 520, 40));

        txtPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 295, 321, 47));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 295, 100, 40));

        btnIniciar.setText("Iniciar Juego");
        btnIniciar.setEnabled(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aladin_room_akinator.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarEnPantalla(){
        lblPregunta.setVisible(true);
        btnSi.setVisible(true);
        btnNo.setVisible(true);
        btnIniciar.setVisible(false);
    }
    
    public void noMostrar(){
        lblPregunta.setVisible(false);
        btnSi.setVisible(false);
        btnNo.setVisible(false);
        btnIniciar.setVisible(false);
    }
    
    
    public String getTextoPersonaje(){
        String txt="";
        
        while(txt.equals("")){
        txt= txtPersonaje.getText();
        txtPersonaje.setText("");
        }
        
        return txt;
    }
    
    public ImageIcon getImgPersonaje(){
        JFileChooser chooser=new JFileChooser();
        int result= chooser.showOpenDialog(null);
        
        if(result==JFileChooser.APPROVE_OPTION){
            File imgSel =chooser.getSelectedFile();
            imgPersonaje = new ImageIcon(imgSel.getPath());
            Image img=imgPersonaje.getImage().getScaledInstance(imagen.getWidth(),imagen.getHeight(), Image.SCALE_SMOOTH);
            imgPersonaje=new ImageIcon(img);
            
        }
        return imgPersonaje;
    }
    
    public void mostrarImagen(ImageIcon image){
        try{
          Image img= image.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_SMOOTH);
          this.imagen.setIcon(new ImageIcon(img));
        }catch(Exception e){
            this.imagen.setIcon(sinImagen());
        }
    }
    
    public ImageIcon sinImagen(){
        ImageIcon image = new ImageIcon(getClass().getResource("/imagenes/noImagenPersonaje.png"));
        Image img=image.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), WIDTH);
        image=new ImageIcon(img);
        return image;
    
    }
    
    
    public void setTextoPersonaje(String Personaje){
        this.txtPersonaje.setText(Personaje);
    }
    
    public String getDescripcion(){
        String desc=null;
        while(desc==null){
        desc=JOptionPane.showInputDialog(null, "ingrese la descripcion del personaje","DESCRIPCION" );
        }
        return desc;
    }
    
    public String getPersonaje(){
        String personaje=null;
        while(personaje==null){
        personaje=JOptionPane.showInputDialog(null, "ingrese el personaje","PERSONAJE" );

        }
        return personaje;
    }
    
    public void setTexto(String text){
        this.lblResultado.setText(text);
    }
    
    public void setlblPregunta(String text){
        this.lblPregunta.setText(text);
    }
    
    public boolean getRespuesta() throws InterruptedException {
        synchronized (this) {
            this.wait();
        }
        return respuesta;
    }
    
    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        respuesta=true;
        synchronized(this){
            this.notify();
        }
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(arbol==null){
            if(txtPersonaje.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Ingrese un personaje");
            }
            else{
            arbol=new arbolAVL(this);
            arbol.arbolInicio(txtPersonaje.getText());
            arbol.setPausado(true);

            JOptionPane.showMessageDialog(this, "se ha ingresado personaje, puedes iniciar a jugar");

            txtPersonaje.setVisible(false);
            btnRegistrar.setVisible(false);
            btnIniciar.setEnabled(true);
            btnIniciar.setVisible(true);
            lblResultado.setVisible(false);

            }
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        mostrarEnPantalla();
        btnSi.setEnabled(true);
        btnNo.setEnabled(true);
        arbol.setPausado(false);
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
    respuesta=false;
    synchronized(this){
        this.notify();
    }
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked

    }//GEN-LAST:event_btnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adivinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtPersonaje;
    // End of variables declaration//GEN-END:variables
}
